---
apiVersion: v2
appVersion: 2022.8.6
description: Home Assistant
name: home-assistant
version: 0.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - home-assistant
  - hass
  - homeassistant
home: https://github.com/daamcus/charts/tree/master/charts/stable/home-assistant
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/519px-Home_Assistant_Logo.svg.png
sources:
  - https://github.com/home-assistant/home-assistant
  - https://github.com/cdr/code-server
  - https://github.com/damacus/charts/tree/master/charts/stable/home-assistant
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.1.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Initial version
