apiVersion: v2
name: supermarket-uploader
description: A Helm chart to upload Cookbooks to a Chef Supermarket

type: application
version: 0.1.0
appVersion: "0.0.1"

annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Initial Release
