apiVersion: v2
name: cluster-issuer
description: Adds letsencrypt issuers for certificate creation
type: application
version: 0.2.0
appVersion: 1.16.0

annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Initial Release
