---
name: "Schedule: Sync labels"

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1" # every Monday at 12pm UTC

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    if: github.repository == 'damacus/charts'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yaml
          delete-other-labels: true
